repositories:
  - name: yogesh-rabbitmq
    url: https://ybhagwatkar.github.io/rabbitmq/.

releases:
  - name: yogesh-rabbitmq
    namespace: yogesh-rabbitmq
    chart: yogesh-rabbitmq/rabbitmq
    set:
    - name: rabbitmq.username
      value: admin
    - name: rabbitmq.password
      value: admin@6666
    - name: rabbitmq.erlangCookie
      value: secretcookie
     
  - name: yogesh-mysql
    namespace: yogesh-mysql
    chart: yogesh-rabbitmq/mysql
   set:
    - name: mysqlRootPassword
      value: yogesh@6666
    - name: mysqlUser
      value: yogesh
    - name: mysqlPassword
      value: yogesh@123
    - name: mysqlDatabase
      value: yogesh

  - name: yogesh-postgresql
    namespace: yogesh-postgresql
    chart: yogesh-rabbitmq/postgresql
    set:
    - name: postgresqlPassword
      value: yogesh@1234
    - name: postgresqlDatabase
      value: yogesh-database

